services:
  # --- BASE DE DATOS (IMAGEN OFICIAL POSTGRESQL) ---
  db:
    image: postgres:17-alpine
    container_name: nutricontrol_db_local
    environment:
      - POSTGRES_USER=${SPRING_DATASOURCE_USERNAME}
      - POSTGRES_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - nutricontrol_postgres_data:/var/lib/postgresql/data
    networks:
      - nutricontrol-net

  # --- TU BACKEND JAVA 25 ---
  backend:
    build: .
    container_name: nutricontrol_backend_local
    ports:
      - "8080:8080"
    depends_on:
      - db
    env_file:
      - .env
    networks:
      - nutricontrol-net

volumes:
  nutricontrol_postgres_data:

networks:
  nutricontrol-net: