spring.application.name=nutricontrol
#spring.datasource.url=jdbc:postgresql://localhost:5432/nutricontrol
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:5432/${DB_NAME}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
nutricontrol.appointments.days=25
nutricontrol.appointments.minutes-gap=35
nutricontrol.appointments.duration-minutes=30
logging.file.name=logs/nutricontrol-app.log
logging.logback.rollingpolicy.file-name-pattern=logs/nutricontrol-app-%d{yyyy-MM-dd}.%i.log
logging.logback.rollingpolicy.max-file-size=10MB
logging.logback.rollingpolicy.max-history=15
logging.logback.rollingpolicy.total-size-cap=1GB
server.forward-headers-strategy=framework
springdoc.api-docs.enabled=false
springdoc.swagger-ui.enabled=false
nutricontrol.appointments.price=50
#SECRETS
# Propiedades sensibles en formato env
spring.security.jwt.secret-key=${APPLICATION_SECURITY_JWT_SECRET_KEY}
spring.security.jwt.expiration=${APPLICATION_SECURITY_JWT_EXPIRATION}
spring.mail.username=${SPRING_MAIL_USERNAME}
spring.mail.password=${SPRING_MAIL_PASSWORD}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
# Propiedades de nutricontrol
nutricontrol.initial-admin.name=${NUTRICONTROL_INITIAL_ADMIN_NAME}
nutricontrol.initial-admin.lastname=${NUTRICONTROL_INITIAL_ADMIN_NAME}
nutricontrol.initial-admin.email=${NUTRICONTROL_INITIAL_ADMIN_EMAIL}
nutricontrol.initial-admin.username=${NUTRICONTROL_INITIAL_ADMIN_USERNAME}
nutricontrol.initial-admin.password=${NUTRICONTROL_INITIAL_ADMIN_PASSWORD}
nutricontrol.initial-admin.timezone=${NUTRICONTROL_INITIAL_ADMIN_TIMEZONE}
nutricontrol.initial-user.name=${NUTRICONTROL_INITIAL_USER_NAME}
nutricontrol.initial-user.lastname=${NUTRICONTROL_INITIAL_USER_LASTNAME}
nutricontrol.initial-user.email=${NUTRICONTROL_INITIAL_USER_EMAIL}
nutricontrol.initial-user.username=${NUTRICONTROL_INITIAL_USER_USERNAME}
nutricontrol.initial-user.password=${NUTRICONTROL_INITIAL_USER_PASSWORD}
nutricontrol.initial-user.timezone=${NUTRICONTROL_INITIAL_USER_TIMEZONE}
# Propiedades de PayPal
paypal.client.id=${PAYPAL_CLIENT_ID}
paypal.client.secret=${PAYPAL_CLIENT_SECRET}
paypal.mode=${PAYPAL_MODE}
paypal.return-url=${PAYPAL_RETURN_URL}
paypal.cancel-url=${PAYPAL_CANCEL_URL}
paypal.webhook.id=${PAYPAL_WEBHOOK_ID}
# Propiedades de Google Meet Mock
google.meet.mock.enabled=${GOOGLE_MEET_MOCK_ENABLED}
# Propiedades de Google OAuth
google.oauth.client-id=${GOOGLE_OAUTH_CLIENT_ID}
google.oauth.client-secret=${GOOGLE_OAUTH_CLIENT_SECRET}
google.oauth.refresh-token=${GOOGLE_OAUTH_REFRESH_TOKEN}

