package com.erick.nutricontrol._enum;

public enum NotificationType {
  USER_APPOINTMENT_CONFIRMED,
  ADMIN_APPOINTMENT_CONFIRMED,
  USER_ADMIN_CANCELLED_APPOINTMENT,
  ADMIN_USER_CANCELLED_APPOINTMENT,
  USER_APPOINTMENT_REMINDER,
  ADMIN_APPOINTMENT_REMINDER,
  PAYMENT_SUCCESS,
  PAYMENT_REFUNDED,
  PAYMENT_FAILED,
  MEDICAL_RECORD_UPDATED
}
